version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: washday
      POSTGRES_USER: washday
      POSTGRES_PASSWORD: washday
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      WASHDAY_SETTINGS_DATABASES: '{"default":{"HOST":"db"}}'
      WASHDAY_SETTINGS_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local
